# backend/docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: square_crm
      POSTGRES_USER: square_user
      POSTGRES_PASSWORD: square_pass
    ports:
      - '9000:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
